# Generated by Django 4.0.10 on 2023-08-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('In Door', 'In Door'), ('Out Door', ' Out Door')], max_length=200, null=True),
        ),
    ]
